<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <EmbeddedResource Include="AssetCatalog\asset_catalog.json" />
    <EmbeddedResource Include="Mapping\default-mapping.json" />
    <EmbeddedResource Include="Mommap\default-canvas.json" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="CoK.OsmImporter.Core.Tests" />
  </ItemGroup>

</Project>
